language: generic
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - texlive-base
    - texlive-font-utils
    - texlive-fonts-extra
    - texlive-fonts-recommended
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-latex-recommended
    - lmodern
    - latex-xcolor
    - pgf
before-script:
  - wget https://github.com/Traap/tlc-article/archive/v1.0.10.tar.gz -O starterkit/tlc-article.tar.gz
  - tar -xvf starterkit/tlc-article.tar.gz .
  - mkdir -p starterkit/_build
script:
  - cd starterkit
  - pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build starterkit.tex
deploy:
  provider: releases
  api_key:
    secure: eJWRL8/fDRKY1+ZdTrzkfSoysaC/MPUG6z4Fux2pBu/ZyMUeoAaom2hj1vunHZY4y8pGVY/7fD120wgD4LXdfdabf2AW2/V/KXaukjanV6hpFdCBW0g7jgSVlrcZ+mfIttH6+qGh+srjb9msv1Gr+LvDWBqoL9eZgxcRAHe/a8zvDV5cQPgH04yl6vTtvFvAejPEkjEmrLn+W/b1rC/OasEZ8rbD7UbuQ/R4tg/uU/KAg6HgNZJl0oMEKKm3HoFRydzUUHb6+UF3eZz6SNBmO2avuPvEeSMw0PEN5tCmzh0qb+UQ8v9WEXxHteXieFja8uDiaWVWE1Fumf+V4/OZTl5pCoplOSAn4RoiUMh/P8IzRDpleFB2EuWilxDHRiOsvwa/UUTGh0ONgstUvTaVa+5DxFQVpOEscaJdkiq8nwK1YGv1tEA05HiUpec7gupopuLyhVzDv4gt7WDVcKD2qpoN+6V/fJOjb06Hta1ZmX5GYSQTEsxxMX+D8hn1PtBsWSBLsEeK2G7s03WqhoTp5Vw1XniSCufKv4GVqi97oJsEMCtqyXqHN78u1zB8YqnRGyM94jr2GIS6npm8hZI2wvO+/dewoG9Appri4S7ocJ43h/u9TG7jUhwBujowxQVNDMMXOsHADGFzmZij3cWJmrkAsp20Zy/1lKkrX5b16yE=
  file: _build/starterkit.pdf
  on:
    repo: Traap/autodoc
notifications:
  email: false
  slack: allanconsulting:FDn63nuwQxikPCD93hza3dk1
