case:
  name: Check Install

  purpose: >
    This protocol is used to demonstrate that the Git software has been properly
    installed and configured. This is done by using Git to configure the
    .gitconfig file and then printing the results of the changes made to
    .gitconfig.

  requirement: IUR01

  steps:
    - confirm: Confirm a developer is able to access Git Help.
      expectation: Git help is displayed.
      sudo: false
      command: git
      argument: help
      evidence: Starts on next line.

    - confirm: A developer is able to initialize the repository.
      expectation: No error.
      sudo: false
      command: git
      argument: init
      evidence: Starts on next line.

    - confirm: A developer is able to configure a Git code pager.
      expectation: No error.
      sudo: false
      command: git
      argument: config --global code.pager cat
      evidence: n/a

    - confirm: A developer is able to configure a Git user name.
      expectation: No error.
      sudo: false
      command: git
      argument: config --global user.name "Gary A. Howard"
      evidence: n/a

    - confirm: A developer is able to configure a Git user email address.
      expectation: No error.
      sudo: false
      command: git
      argument: config --global user.email gary.a.howard@mac.com
      evidence: Starts on next line.

    - confirm: A developer is able to configure a Git credentials.
      expectation: No error.
      sudo: false
      command: git
      argument: config --global credential.helper store
      evidence: n/a

    - confirm: Confirm a developer has a properly configured .gitconfig file.
      expectation: .gitconfig file is displayed.
      sudo: false
      command: cat
      argument: .git/config
      evidence: Starts on next line.
